---
- block:
    - name: include OS-specific vars for GUI
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
            - "{{ ansible_distribution }}.yml"
            - "{{ ansible_os_family }}.yml"
          skip: true

    - import_tasks: package.yml
    - import_tasks: account.yml
    - import_tasks: faxocr.yml
    - import_tasks: startup.yml

  tags:
    - gui
