---
- name: install packages for desktop
  apt:
    name: "{{ desktop_package }}"

- name: install web browser packages
  apt:
    name: "{{ web_browser_package }}"

- name: install editor packages for desktop
  apt:
    name:
      - emacs
      - vim

- name: remove packages
  apt:
    name:
      - unattended-upgrades
    state: absent

- name: disable auto package upgrades
  template:
    dest: /etc/apt/apt.conf.d/80auto-upgrades-disable
    src: 80auto-upgrades-disable.j2
    owner: root
    group: root
    mode: 0644

- name: disable auto release upgrades
  lineinfile:
    path: /etc/update-manager/release-upgrades
    regexp: ^Prompt=
    line: Prompt=never
    backup: yes
  when:
    ansible_distribution == 'Ubuntu'
