---
# tasks file for roles/common
- name: update apt cache and upgrade installed packages
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 36000

- name: install initial packages for ansible
  apt:
    name:
      - sudo
      - git
