---
- name: set libtool package name
  set_fact:
    _libtool_package: libtool
  when:
    - ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version(14, '<=') or
      ansible_distribution == 'Debian' and ansible_distribution_major_version is version(7, '<=')


- name: setup software building environment
  apt:
    name:
      - build-essential
      - autoconf
      - "{{ _libtool_package | default('libtool-bin') }}"
