---
- block:
    - name: set wkhtmltopdf version for older environment
      set_fact:
        wkhtmltopdf_version: '0.12.1'
        _wkhtmltopdf_version_delimiter: '-'
        _wkhtmltopdf_os_type: _linux-
        _wkhtmltopdf_packaging: wkhtmltopdf
      when:
        - wkhtmltopdf_version is not defined
        - ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version(16, '<') or
          ansible_distribution == 'Debian' and ansible_distribution_major_version is version(9, '<') or
          ansible_distribution == 'CentOS' and ansible_distribution_major_version is version(6, '<')

    - name: set wkhtmltopdf version for newer environment
      set_fact:
        wkhtmltopdf_version: '0.12.1.4-2'
        _wkhtmltopdf_version_delimiter: _
        _wkhtmltopdf_os_type: .
        _wkhtmltopdf_packaging: packaging
      when:
        - wkhtmltopdf_version is not defined
        - ansible_distribution == 'Ubuntu' and ansible_distribution_major_version is version(16, '>=') or
          ansible_distribution == 'Debian' and ansible_distribution_major_version is version(9, '>=') or
          ansible_distribution == 'CentOS' and ansible_distribution_major_version is version(6, '>=')
          # as of Ubuntu 18.04, CentOS 7, Debian 10

    - name: install {{ wkhtmltopdf_archive }}
      apt:
        deb: "{{ wkhtmltopdf_url }}"
        state: present

  tags:
    - wkhtmltopdf
